# Generated by Django 4.2.7 on 2024-03-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absence',
            new_name='Absence_School',
        ),
        migrations.RenameModel(
            old_name='BulletinScolaire',
            new_name='BulletinScolaire_School',
        ),
        migrations.RenameModel(
            old_name='Classe',
            new_name='Classe_School',
        ),
        migrations.RenameModel(
            old_name='EmployeAdministratif',
            new_name='EmployeAdministratif_School',
        ),
        migrations.RenameModel(
            old_name='Evenement',
            new_name='Evenement_School',
        ),
        migrations.RenameModel(
            old_name='Matiere',
            new_name='Matiere_School',
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='Note_School',
        ),
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Paiement_School',
        ),
        migrations.RenameModel(
            old_name='Enseignant',
            new_name='Enseignant_School',
        ),
        migrations.RenameModel(
            old_name='Etudiant',
            new_name='Etudiant_School',
        ),
        migrations.CreateModel(
            name='Message_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('Admin_School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_Management.admin_school')),
                ('Enseignant_School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_Management.enseignant_school')),
                ('Etudiant_School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_Management.etudiant_school')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_Management.site_school_management')),
            ],
        ),
        migrations.CreateModel(
            name='Infos_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=50)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('Bio', models.CharField(max_length=255, null=True)),
                ('Infos_supplementaires', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_Management.site_school_management')),
            ],
        ),
    ]
