# Generated by Django 4.2.7 on 2024-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignants',
            name='adresse',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignants',
            name='nombres_heures',
            field=models.IntegerField(null=True),
        ),
    ]
