# Generated by Django 4.2.7 on 2024-03-12 05:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('montan_total', models.FloatField()),
                ('date_commande', models.DateTimeField()),
                ('statu_commande', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('stock', models.CharField(max_length=50)),
                ('image_produit', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_reduction', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produits')),
            ],
        ),
        migrations.AddField(
            model_name='produits',
            name='id_site_ecom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.type'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produits')),
                ('id_utilisateurB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_etoiles', models.IntegerField(choices=[(1, 'Une étoile'), (2, 'Deux étoiles'), (3, 'Trois étoiles'), (4, 'Quatre étoiles'), (5, 'Cinq étoiles')])),
                ('id_utilisateurB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('contenu', models.TextField()),
                ('statu', models.BooleanField(default=False)),
                ('id_utilisateurA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_main')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_liv', models.DateTimeField()),
                ('Lieu', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=False)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.commande')),
                ('id_utilisateurC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_commentaire', models.DateTimeField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produits')),
                ('id_utilisateurB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_standard')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='id_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produits'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_utilisateurB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_standard'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('date_avis', models.DateTimeField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produits')),
                ('id_utilisateurB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_standard')),
            ],
        ),
    ]
