# Generated by Django 4.2.7 on 2024-03-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='id_utilisateurB',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_utilisateurB',
        ),
        migrations.RemoveField(
            model_name='commentaires',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='commentaires',
            name='id_utilisateurB',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id_commande',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id_utilisateurC',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_utilisateurA',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='id_utilisateurB',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='id_utilisateurB',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='id_site_ecom',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='id_produit',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Commentaires',
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='Produits',
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
