# Generated by Django 4.2.7 on 2024-05-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('sitewebpam', '0002_info_utilisateurs_image_info_utilisateurs_initials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('couleur', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_sitepam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portofolios', to='sitewebpam.sitewebpam')),
            ],
        ),
        migrations.CreateModel(
            name='User_Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_utilisateur', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('id_sitepam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_users', to='sitewebpam.sitewebpam')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_users', to='portofolio.site_portofolio')),
            ],
        ),
        migrations.CreateModel(
            name='Services_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='services_images/')),
                ('descriptions', models.CharField(max_length=255, null=True)),
                ('autres', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='services_images/')),
                ('descriptions', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('links', models.CharField(max_length=255, null=True)),
                ('categorie', models.CharField(max_length=100, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
        migrations.CreateModel(
            name='Partage_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.pro_portofolio')),
                ('data_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('User_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.user_standard')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.user_standard')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.pro_portofolio')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.user_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Infos_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=50)),
                ('prenom', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('adresse', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
        migrations.CreateModel(
            name='Heroes_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre1', models.CharField(max_length=50)),
                ('titre2', models.CharField(max_length=50, null=True)),
                ('paragraphe', models.CharField(max_length=255, null=True)),
                ('cv', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
        migrations.CreateModel(
            name='Follower_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('User_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.user_standard')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('autre', models.TextField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
    ]
