# Generated by Django 4.2.7 on 2024-05-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_portofolio',
            name='image',
            field=models.ImageField(null=True, upload_to='services_images/'),
        ),
        migrations.AddField(
            model_name='heroes_portofolio',
            name='image',
            field=models.ImageField(null=True, upload_to='services_images/'),
        ),
    ]
