# Generated by Django 5.0.3 on 2024-05-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_about_portofolio_image_heroes_portofolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_portofolio',
            name='logo',
            field=models.ImageField(null=True, upload_to='services_images/'),
        ),
    ]
