# Generated by Django 4.2.7 on 2024-05-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_alter_about_portofolio_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etude_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=50, null=True)),
                ('ecole', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
        migrations.CreateModel(
            name='Carriere_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=50, null=True)),
                ('compagnie', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
    ]
