# Generated by Django 4.2.7 on 2024-05-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0006_alter_carriere_portofolio_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('pourcentage', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
    ]
