# Generated by Django 4.2.7 on 2024-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0009_contact_email_portofolio_nomcomplet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_email_portofolio',
            name='email_proprio',
        ),
    ]
