# Generated by Django 4.2.7 on 2024-05-21 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0010_remove_contact_email_portofolio_email_proprio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_Site_Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_choice', models.CharField(default='navbar1', max_length=255)),
                ('header_choice', models.CharField(default='header1', max_length=255)),
                ('about_choice', models.CharField(max_length=255, null=True)),
                ('service_choice', models.CharField(default='service1', max_length=255)),
                ('skill_choice', models.CharField(max_length=255, null=True)),
                ('experience_choice', models.CharField(max_length=255, null=True)),
                ('projet_choice', models.CharField(max_length=255, null=True)),
                ('contact_choice', models.CharField(default='contact1', max_length=255)),
                ('footer_choice', models.CharField(default='footer1', max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.site_portofolio')),
            ],
        ),
    ]
