# Generated by Django 4.2.7 on 2024-03-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_utilisateur', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('portable', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=55)),
                ('date_de_nais', models.DateField()),
                ('date_creation', models.DateField()),
                ('statu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_utilisateur', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('portable', models.CharField(max_length=20)),
                ('date_de_nais', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_utilisateur', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('portable', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=55)),
                ('date_de_nais', models.DateField()),
                ('statu', models.BooleanField(default=False)),
            ],
        ),
    ]
