# Generated by Django 4.2.7 on 2024-06-04 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_main',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user_main',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_main',
            name='grade',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
