# Generated by Django 4.2.7 on 2024-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_main',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
