# Generated by Django 4.2.7 on 2024-03-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_user_main_options_alter_user_main_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_main',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user_main',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user_main',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_main',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_main',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user_main',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
