# Generated by Django 4.2.7 on 2024-03-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_user_main_options_alter_user_main_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_main',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_main',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_main',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_main',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_main',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_main',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
