# Generated by Django 4.2.7 on 2024-03-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_user_main_adresse_user_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_main',
            name='date_de_nais',
            field=models.DateField(blank=True, null=True),
        ),
    ]
