# Generated by Django 4.2.7 on 2024-03-21 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_user_main_date_de_nais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_main',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='user_main',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user_main',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_main',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user_main',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='user_main',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='user_main',
            name='date_de_nais',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_main',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
