# Generated by Django 4.2.7 on 2024-06-04 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('sitewebpam', '0003_plan_alter_abonement_date_debut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Site_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Couleur', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='site_blogs', to='blog.category_blog')),
                ('id_Admin_Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_sitepam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='site_blog',
            name='tags',
            field=models.ManyToManyField(related_name='site_blogs', to='blog.tag_blog'),
        ),
        migrations.CreateModel(
            name='Post_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='blog.category_blog')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('tags', models.ManyToManyField(to='blog.tag_blog')),
            ],
        ),
        migrations.CreateModel(
            name='Partage_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog')),
                ('data_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blog.user_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Note_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Like_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Infos_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=50, null=True)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('Bio', models.CharField(max_length=255, null=True)),
                ('Infos_supplementaires', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
            ],
        ),
        migrations.CreateModel(
            name='Follower_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog')),
            ],
        ),
    ]
