# Generated by Django 4.2.7 on 2024-06-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_bg', models.CharField(default='color', max_length=50)),
                ('navbar_font', models.CharField(max_length=50)),
                ('navbar_font_size', models.CharField(default='16px', max_length=50)),
                ('navbar_brand', models.CharField(max_length=50, null=True)),
                ('navbar_brand_color', models.CharField(default='color', max_length=50, null=True)),
                ('navbar_link_color', models.CharField(default='color', max_length=50, null=True)),
                ('navbar_link_1', models.CharField(max_length=50, null=True)),
                ('navbar_link_2', models.CharField(max_length=50, null=True)),
                ('navbar_link_3', models.CharField(max_length=50, null=True)),
                ('navbar_link_4', models.CharField(max_length=50, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
            ],
        ),
    ]
