# Generated by Django 4.2.7 on 2024-03-08 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_blog',
            name='Couleur',
        ),
        migrations.RemoveField(
            model_name='site_blog',
            name='logo',
        ),
        migrations.AddField(
            model_name='site_blog',
            name='Couleur',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site_blog',
            name='logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
