# Generated by Django 4.2.7 on 2024-03-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('sitewebpam', '0001_initial'),
        ('blog', '0002_remove_site_blog_couleur_remove_site_blog_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=50, null=True)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('Bio', models.CharField(max_length=255, null=True)),
                ('Infos_supplementaires', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
            ],
        ),
        migrations.CreateModel(
            name='Partage_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_Blog',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_Blog',
        ),
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follower_Blog',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='Like_Blog',
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='Note_Blog',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tag_Blog',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_Blog',
        ),
        migrations.DeleteModel(
            name='Partage',
        ),
        migrations.AddField(
            model_name='partage_blog',
            name='data_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog'),
        ),
        migrations.AddField(
            model_name='partage_blog',
            name='data_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam'),
        ),
        migrations.AddField(
            model_name='partage_blog',
            name='user_Standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_standard'),
        ),
        migrations.AddField(
            model_name='partage_blog',
            name='user_livreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur'),
        ),
        migrations.AddField(
            model_name='partage_blog',
            name='user_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_main'),
        ),
    ]
