# Generated by Django 4.2.7 on 2024-06-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sitechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitechoice',
            name='navbar_brand_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitechoice',
            name='navbar_font_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitechoice',
            name='navbar_link_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
