# Generated by Django 4.2.7 on 2024-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_sitechoice_navbar_brand_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitechoice',
            name='navbar_link_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
