# Generated by Django 4.2.7 on 2024-03-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_infos_blog_partage_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower_blog',
            old_name='User_Standard',
            new_name='user_Standard',
        ),
        migrations.RenameField(
            model_name='note_blog',
            old_name='User_Standard',
            new_name='user_Standard',
        ),
    ]
