# Generated by Django 4.2.7 on 2024-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_user_standard_follower_blog_user_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post_blog',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='site_blog',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
