# Generated by Django 4.2.7 on 2024-03-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(max_length=50)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_main')),
            ],
        ),
        migrations.CreateModel(
            name='Sitewebpam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domaine', models.CharField(max_length=100)),
                ('nom_site', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('stockage', models.CharField(max_length=150)),
                ('id_bonnemnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.abonement')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_main')),
            ],
        ),
    ]
