# Generated by Django 4.2.7 on 2024-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebpam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_utilisateurs',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='info_utilisateurs',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
