# Generated by Django 4.2.7 on 2024-03-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebpam', '0002_info_utilisateurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_utilisateurs',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sitewebpam',
            name='id_bonnemnet',
        ),
        migrations.AddField(
            model_name='sitewebpam',
            name='id_abonnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.abonement'),
        ),
    ]
