# Generated by Django 4.2.7 on 2024-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebpam', '0005_sitewebpam_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitewebpam',
            name='nom_site',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
