# Generated by Django 4.2.7 on 2024-03-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebpam', '0006_alter_sitewebpam_nom_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitewebpam',
            old_name='Domaine',
            new_name='domaine',
        ),
    ]
