# Generated by Django 4.2.7 on 2024-07-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_hospital_management',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
